/* Generated by Pyrex 0.9.2.1 on Thu Feb 28 09:37:56 2008 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#include "../cuckoo_hash/cuckoo_hash.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void **vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
staticforward char **__pyx_f;

static char __pyx_mdoc[] = "Cuckoo Hash library\n\nThis module provides a simple interface to the Cuckoo Hash,\nan efficient sparse array implementation.\n\nCuckoo Hashing was proposed by Pagh and Rodler (2001). The idea is to\nbuild a dictionary data structure with two hash tables and two different\nhash functions.\n\nSEE ALSO\nRasmus Pagh and Flemming Friche Rodler. 2001. Cuckoo Hashing, Proceedings\nof ESA 2001, Lecture Notes in Computer Science, vol. 2161.\n\nChuleerat Jaruskulchai and Canasai Kruengkrai. 2002. Building Inverted\nFiles Through Efficient Dynamic Hashing. Proceedings of the Fifth National\nComputer Science and Engineering Conference (NCSEC-2002).\n\nL Devroye, P Morin. 2003. Cuckoo hashing: Further analysis. Information \nProcessing Letters.\n\n\nThis Python interface is to CKHash 0.4.2:\n * Copyright (C) 2005-2008 Thai Computational Linguistics Laboratory (TCL),\n * National Institute of Information and Communications Technology (NICT)\n * Written by Canasai Kruengkrai <canasaiREMOVETHIS@gmail.com>\n";

/* Declarations from cuckoo */

staticforward PyTypeObject __pyx_type_6cuckoo_cuckoohash;

struct __pyx_obj_6cuckoo_cuckoohash {
  PyObject_HEAD
  struct __pyx_vtabstruct_6cuckoo_cuckoohash *__pyx_vtab;
  struct CKHash_Table_t (*table);
};

struct __pyx_vtabstruct_6cuckoo_cuckoohash {
  PyObject *((*__cuckoo_gather)(struct __pyx_obj_6cuckoo_cuckoohash *,int ((char (*),int ,void (*)))));
};
static struct __pyx_vtabstruct_6cuckoo_cuckoohash *__pyx_vtabptr_6cuckoo_cuckoohash;

static PyTypeObject *__pyx_ptype_6cuckoo_cuckoohash = 0;
static PyObject *__pyx_k6;
static PyObject *__pyx_k7;
static int (__pyx_f_6cuckoo__cuckoo_get_keys(char (*),int ,void (*))); /*proto*/
static int (__pyx_f_6cuckoo__cuckoo_get_values(char (*),int ,void (*))); /*proto*/
static int (__pyx_f_6cuckoo__cuckoo_get_items(char (*),int ,void (*))); /*proto*/

/* Implementation of cuckoo */

char (__pyx_k1[]) = "Jose Nazario <jose@monkey.org>";
char (__pyx_k2[]) = "Copyright (c) 2008 Jose Nazario";
char (__pyx_k4[]) = "";
char (__pyx_k5[]) = "1.0-0.4.2";

static PyObject *__pyx_n___author__;
static PyObject *__pyx_n___copyright__;
static PyObject *__pyx_n___license__;
static PyObject *__pyx_n___url__;
static PyObject *__pyx_n___version__;
static PyObject *__pyx_n_GPL2;

static PyObject *__pyx_k1p;
static PyObject *__pyx_k2p;
static PyObject *__pyx_k4p;
static PyObject *__pyx_k5p;

static PyObject *__pyx_n_append;

static int __pyx_f_6cuckoo__cuckoo_get_keys(char (*__pyx_v_key),int __pyx_v_val,void (*__pyx_v_arg)) {
  PyObject *__pyx_v_lst;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  __pyx_v_lst = Py_None; Py_INCREF(__pyx_v_lst);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":75 */
  __pyx_1 = (PyObject *)__pyx_v_arg;
  Py_INCREF(__pyx_1);
  Py_DECREF(__pyx_v_lst);
  __pyx_v_lst = __pyx_1;
  __pyx_1 = 0;

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":76 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_lst, __pyx_n_append); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  __pyx_2 = PyString_FromString(__pyx_v_key); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_WriteUnraisable("cuckoo._cuckoo_get_keys");
  __pyx_L0:;
  Py_DECREF(__pyx_v_lst);
  return __pyx_r;
}

static int __pyx_f_6cuckoo__cuckoo_get_values(char (*__pyx_v_key),int __pyx_v_val,void (*__pyx_v_arg)) {
  PyObject *__pyx_v_lst;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  __pyx_v_lst = Py_None; Py_INCREF(__pyx_v_lst);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":79 */
  __pyx_1 = (PyObject *)__pyx_v_arg;
  Py_INCREF(__pyx_1);
  Py_DECREF(__pyx_v_lst);
  __pyx_v_lst = __pyx_1;
  __pyx_1 = 0;

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":80 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_lst, __pyx_n_append); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  __pyx_2 = (PyObject *)__pyx_v_val;
  Py_INCREF(__pyx_2);
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_WriteUnraisable("cuckoo._cuckoo_get_values");
  __pyx_L0:;
  Py_DECREF(__pyx_v_lst);
  return __pyx_r;
}

static int __pyx_f_6cuckoo__cuckoo_get_items(char (*__pyx_v_key),int __pyx_v_val,void (*__pyx_v_arg)) {
  PyObject *__pyx_v_lst;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_v_lst = Py_None; Py_INCREF(__pyx_v_lst);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":83 */
  __pyx_1 = (PyObject *)__pyx_v_arg;
  Py_INCREF(__pyx_1);
  Py_DECREF(__pyx_v_lst);
  __pyx_v_lst = __pyx_1;
  __pyx_1 = 0;

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":84 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_lst, __pyx_n_append); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  __pyx_2 = PyString_FromString(__pyx_v_key); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  __pyx_3 = (PyObject *)__pyx_v_val;
  Py_INCREF(__pyx_3);
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
  __pyx_4 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_WriteUnraisable("cuckoo._cuckoo_get_items");
  __pyx_L0:;
  Py_DECREF(__pyx_v_lst);
  return __pyx_r;
}

static PyObject *__pyx_n_len;
static PyObject *__pyx_n_insert;

static int __pyx_f_6cuckoo_10cuckoohash___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_6cuckoo_10cuckoohash___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_size = 0;
  PyObject *__pyx_v_seq = 0;
  PyObject *__pyx_v_k;
  PyObject *__pyx_v_v;
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"size","seq",0};
  __pyx_v_size = __pyx_k6;
  __pyx_v_seq = __pyx_k7;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|OO", __pyx_argnames, &__pyx_v_size, &__pyx_v_seq)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_size);
  Py_INCREF(__pyx_v_seq);
  __pyx_v_k = Py_None; Py_INCREF(__pyx_v_k);
  __pyx_v_v = Py_None; Py_INCREF(__pyx_v_v);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":102 */
  __pyx_1 = PyInt_AsLong(__pyx_v_size); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
  ((struct __pyx_obj_6cuckoo_cuckoohash *)__pyx_v_self)->table = ckh_construct_table(__pyx_1);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":103 */
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  Py_INCREF(__pyx_v_seq);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_seq);
  __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_4, __pyx_2, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  __pyx_1 = __pyx_1 > 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (__pyx_1) {

    /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":104 */
    __pyx_3 = PyObject_GetIter(__pyx_v_seq); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
    for (;;) {
      __pyx_L3:;
      __pyx_4 = PyIter_Next(__pyx_3);
      if (!__pyx_4) {
        if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
        break;
      }
      __pyx_2 = __Pyx_UnpackItem(__pyx_4, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
      Py_DECREF(__pyx_v_k);
      __pyx_v_k = __pyx_2;
      __pyx_2 = 0;
      __pyx_5 = __Pyx_UnpackItem(__pyx_4, 1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
      Py_DECREF(__pyx_v_v);
      __pyx_v_v = __pyx_5;
      __pyx_5 = 0;
      if (__Pyx_EndUnpack(__pyx_4, 2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __pyx_4 = PyObject_GetAttr(__pyx_v_self, __pyx_n_insert); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
      __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
      Py_INCREF(__pyx_v_k);
      PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_k);
      Py_INCREF(__pyx_v_v);
      PyTuple_SET_ITEM(__pyx_2, 1, __pyx_v_v);
      __pyx_5 = PyObject_CallObject(__pyx_4, __pyx_2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
    }
    __pyx_L4:;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("cuckoo.cuckoohash.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_k);
  Py_DECREF(__pyx_v_v);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_size);
  Py_DECREF(__pyx_v_seq);
  return __pyx_r;
}

static PyObject *__pyx_f_6cuckoo_10cuckoohash___del__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6cuckoo_10cuckoohash___del__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":107 */
  ckh_destruct_table(((struct __pyx_obj_6cuckoo_cuckoohash *)__pyx_v_self)->table);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("cuckoo.cuckoohash.__del__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static int __pyx_f_6cuckoo_10cuckoohash___len__(PyObject *__pyx_v_self); /*proto*/
static int __pyx_f_6cuckoo_10cuckoohash___len__(PyObject *__pyx_v_self) {
  int __pyx_r;
  Py_INCREF(__pyx_v_self);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":110 */
  __pyx_r = cuckoo_table_size(((struct __pyx_obj_6cuckoo_cuckoohash *)__pyx_v_self)->table);
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("cuckoo.cuckoohash.__len__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_get;

static PyObject *__pyx_f_6cuckoo_10cuckoohash___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_key); /*proto*/
static PyObject *__pyx_f_6cuckoo_10cuckoohash___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_key) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_key);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":113 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_get); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  Py_INCREF(__pyx_v_key);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_key);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("cuckoo.cuckoohash.__getitem__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_key);
  return __pyx_r;
}

static int __pyx_f_6cuckoo_10cuckoohash___setitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_key, PyObject *__pyx_v_value); /*proto*/
static int __pyx_f_6cuckoo_10cuckoohash___setitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_key, PyObject *__pyx_v_value) {
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_key);
  Py_INCREF(__pyx_v_value);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":116 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_insert); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
  Py_INCREF(__pyx_v_key);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_key);
  Py_INCREF(__pyx_v_value);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_v_value);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("cuckoo.cuckoohash.__setitem__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_key);
  Py_DECREF(__pyx_v_value);
  return __pyx_r;
}

static PyObject *__pyx_n_delete;

static int __pyx_f_6cuckoo_10cuckoohash___delitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_key); /*proto*/
static int __pyx_f_6cuckoo_10cuckoohash___delitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_key) {
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_key);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":119 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_delete); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  Py_INCREF(__pyx_v_key);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_key);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("cuckoo.cuckoohash.__delitem__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_key);
  return __pyx_r;
}

static PyObject *__pyx_f_6cuckoo_10cuckoohash_delete(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6cuckoo_10cuckoohash_delete[] = "delete(key)\n\n        delete the specified key";
static PyObject *__pyx_f_6cuckoo_10cuckoohash_delete(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char (*__pyx_v_key);
  int __pyx_v_ret;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"key",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "s", __pyx_argnames, &__pyx_v_key)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":126 */
  ckh_get(((struct __pyx_obj_6cuckoo_cuckoohash *)__pyx_v_self)->table,__pyx_v_key,(&__pyx_v_ret));

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":127 */
  __pyx_1 = PyInt_FromLong(((int )((void (*))__pyx_v_ret))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  Py_DECREF(__pyx_1);
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":128 */
  ckh_delete(((struct __pyx_obj_6cuckoo_cuckoohash *)__pyx_v_self)->table,__pyx_v_key);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("cuckoo.cuckoohash.delete");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_6cuckoo_10cuckoohash_lookup(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6cuckoo_10cuckoohash_lookup[] = "lookup(key)\n\n        test to see if the key is present in the hash table";
static PyObject *__pyx_f_6cuckoo_10cuckoohash_lookup(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char (*__pyx_v_key);
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"key",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "s", __pyx_argnames, &__pyx_v_key)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":134 */
  __pyx_1 = PyInt_FromLong(ckh_lookup(((struct __pyx_obj_6cuckoo_cuckoohash *)__pyx_v_self)->table,__pyx_v_key)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("cuckoo.cuckoohash.lookup");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_lookup;

static PyObject *__pyx_f_6cuckoo_10cuckoohash_has_key(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6cuckoo_10cuckoohash_has_key[] = "has_key(key)\n\n        a synonym for lookup(key)";
static PyObject *__pyx_f_6cuckoo_10cuckoohash_has_key(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char (*__pyx_v_key);
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"key",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "s", __pyx_argnames, &__pyx_v_key)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":140 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_lookup); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  __pyx_2 = PyString_FromString(__pyx_v_key); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("cuckoo.cuckoohash.has_key");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_6cuckoo_10cuckoohash_insert(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6cuckoo_10cuckoohash_insert[] = "insert(key, val)\n\n        insert the key:value pair into the hash table.\n	key - a string\n	val - any Python object";
static PyObject *__pyx_f_6cuckoo_10cuckoohash_insert(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char (*__pyx_v_key);
  PyObject *__pyx_v_val = 0;
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {"key","val",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "sO", __pyx_argnames, &__pyx_v_key, &__pyx_v_val)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_val);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":148 */
  Py_INCREF(__pyx_v_val);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":149 */
  ckh_insert(((struct __pyx_obj_6cuckoo_cuckoohash *)__pyx_v_self)->table,__pyx_v_key,((int )((void (*))__pyx_v_val)));

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("cuckoo.cuckoohash.insert");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_val);
  return __pyx_r;
}

static PyObject *__pyx_f_6cuckoo_10cuckoohash_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6cuckoo_10cuckoohash_get[] = "get(key)\n\n        retriee the value for the specified key";
static PyObject *__pyx_f_6cuckoo_10cuckoohash_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char (*__pyx_v_key);
  int __pyx_v_ret;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"key",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "s", __pyx_argnames, &__pyx_v_key)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":156 */
  ckh_get(((struct __pyx_obj_6cuckoo_cuckoohash *)__pyx_v_self)->table,__pyx_v_key,(&__pyx_v_ret));

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":157 */
  __pyx_1 = (PyObject *)__pyx_v_ret;
  Py_INCREF(__pyx_1);
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("cuckoo.cuckoohash.get");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_6cuckoo_10cuckoohash___cuckoo_gather(struct __pyx_obj_6cuckoo_cuckoohash *__pyx_v_self,int (__pyx_v_gatherfunc(char (*),int ,void (*)))) {
  PyObject *__pyx_v_l;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_l = Py_None; Py_INCREF(__pyx_v_l);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":161 */
  __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
  Py_DECREF(__pyx_v_l);
  __pyx_v_l = __pyx_1;
  __pyx_1 = 0;

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":162 */
  cuckoo_apply(__pyx_v_self->table,__pyx_v_gatherfunc,((void (*))__pyx_v_l));

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":163 */
  Py_INCREF(__pyx_v_l);
  __pyx_r = __pyx_v_l;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("cuckoo.cuckoohash.__cuckoo_gather");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_l);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_6cuckoo_10cuckoohash_keys(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6cuckoo_10cuckoohash_keys[] = "keys() - the list of keys for the hash table";
static PyObject *__pyx_f_6cuckoo_10cuckoohash_keys(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":167 */
  __pyx_1 = ((struct __pyx_vtabstruct_6cuckoo_cuckoohash *)((struct __pyx_obj_6cuckoo_cuckoohash *)__pyx_v_self)->__pyx_vtab)->__cuckoo_gather(((struct __pyx_obj_6cuckoo_cuckoohash *)__pyx_v_self),__pyx_f_6cuckoo__cuckoo_get_keys); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("cuckoo.cuckoohash.keys");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_6cuckoo_10cuckoohash_values(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6cuckoo_10cuckoohash_values[] = "values() - the list of values held in the hash table";
static PyObject *__pyx_f_6cuckoo_10cuckoohash_values(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":171 */
  __pyx_1 = ((struct __pyx_vtabstruct_6cuckoo_cuckoohash *)((struct __pyx_obj_6cuckoo_cuckoohash *)__pyx_v_self)->__pyx_vtab)->__cuckoo_gather(((struct __pyx_obj_6cuckoo_cuckoohash *)__pyx_v_self),__pyx_f_6cuckoo__cuckoo_get_values); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 171; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("cuckoo.cuckoohash.values");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_6cuckoo_10cuckoohash_items(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6cuckoo_10cuckoohash_items[] = "C.items() -> list of (key, value) pairs in C";
static PyObject *__pyx_f_6cuckoo_10cuckoohash_items(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":175 */
  __pyx_1 = ((struct __pyx_vtabstruct_6cuckoo_cuckoohash *)((struct __pyx_obj_6cuckoo_cuckoohash *)__pyx_v_self)->__pyx_vtab)->__cuckoo_gather(((struct __pyx_obj_6cuckoo_cuckoohash *)__pyx_v_self),__pyx_f_6cuckoo__cuckoo_get_items); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 175; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("cuckoo.cuckoohash.items");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_iter;
static PyObject *__pyx_n_keys;

static PyObject *__pyx_f_6cuckoo_10cuckoohash___iter__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_6cuckoo_10cuckoohash___iter__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":178 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_iter); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_keys); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
  __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
  __pyx_4 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("cuckoo.cuckoohash.__iter__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_items;

static PyObject *__pyx_f_6cuckoo_10cuckoohash_iteritems(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6cuckoo_10cuckoohash_iteritems[] = "C.iteritems() -> iterate over the (key, value) items in C";
static PyObject *__pyx_f_6cuckoo_10cuckoohash_iteritems(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":182 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_iter); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_items); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; goto __pyx_L1;}
  __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
  __pyx_4 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("cuckoo.cuckoohash.iteritems");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_6cuckoo_10cuckoohash_iterkeys(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6cuckoo_10cuckoohash_iterkeys[] = "C.iterkeys() -> iterate over the keys in C";
static PyObject *__pyx_f_6cuckoo_10cuckoohash_iterkeys(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":186 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_iter); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 186; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 186; goto __pyx_L1;}
  Py_INCREF(__pyx_v_self);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_self);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 186; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("cuckoo.cuckoohash.iterkeys");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_values;

static PyObject *__pyx_f_6cuckoo_10cuckoohash_itervalues(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6cuckoo_10cuckoohash_itervalues[] = "C.itervalues() -> iterate over the value in C";
static PyObject *__pyx_f_6cuckoo_10cuckoohash_itervalues(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":190 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_iter); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_values); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; goto __pyx_L1;}
  __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
  __pyx_4 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("cuckoo.cuckoohash.itervalues");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_GPL2, "GPL2"},
  {&__pyx_n___author__, "__author__"},
  {&__pyx_n___copyright__, "__copyright__"},
  {&__pyx_n___license__, "__license__"},
  {&__pyx_n___url__, "__url__"},
  {&__pyx_n___version__, "__version__"},
  {&__pyx_n_append, "append"},
  {&__pyx_n_delete, "delete"},
  {&__pyx_n_get, "get"},
  {&__pyx_n_insert, "insert"},
  {&__pyx_n_items, "items"},
  {&__pyx_n_iter, "iter"},
  {&__pyx_n_keys, "keys"},
  {&__pyx_n_len, "len"},
  {&__pyx_n_lookup, "lookup"},
  {&__pyx_n_values, "values"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k1p, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_k2p, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_k4p, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_k5p, __pyx_k5, sizeof(__pyx_k5)},
  {0, 0, 0}
};
static struct __pyx_vtabstruct_6cuckoo_cuckoohash __pyx_vtable_6cuckoo_cuckoohash;

static PyObject *__pyx_tp_new_6cuckoo_cuckoohash(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_6cuckoo_cuckoohash *p = (struct __pyx_obj_6cuckoo_cuckoohash *)o;
  (struct __pyx_vtabstruct_6cuckoo_cuckoohash *)p->__pyx_vtab = __pyx_vtabptr_6cuckoo_cuckoohash;
  return o;
}

static void __pyx_tp_dealloc_6cuckoo_cuckoohash(PyObject *o) {
  struct __pyx_obj_6cuckoo_cuckoohash *p = (struct __pyx_obj_6cuckoo_cuckoohash *)o;
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_6cuckoo_cuckoohash(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_6cuckoo_cuckoohash *p = (struct __pyx_obj_6cuckoo_cuckoohash *)o;
  return 0;
}

static int __pyx_tp_clear_6cuckoo_cuckoohash(PyObject *o) {
  struct __pyx_obj_6cuckoo_cuckoohash *p = (struct __pyx_obj_6cuckoo_cuckoohash *)o;
  return 0;
}
static PyObject *__pyx_sq_item_6cuckoo_cuckoohash(PyObject *o, int i) {
  PyObject *r;
  PyObject *x = PyInt_FromLong(i); if(!x) return 0;
  r = o->ob_type->tp_as_mapping->mp_subscript(o, x);
  Py_DECREF(x);
  return r;
}

static int __pyx_mp_ass_subscript_6cuckoo_cuckoohash(PyObject *o, PyObject *i, PyObject *v) {
  if (v) {
    return __pyx_f_6cuckoo_10cuckoohash___setitem__(o, i, v);
  }
  else {
    return __pyx_f_6cuckoo_10cuckoohash___delitem__(o, i);
  }
}

static struct PyMethodDef __pyx_methods_6cuckoo_cuckoohash[] = {
  {"__del__", (PyCFunction)__pyx_f_6cuckoo_10cuckoohash___del__, METH_VARARGS|METH_KEYWORDS, 0},
  {"delete", (PyCFunction)__pyx_f_6cuckoo_10cuckoohash_delete, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6cuckoo_10cuckoohash_delete},
  {"lookup", (PyCFunction)__pyx_f_6cuckoo_10cuckoohash_lookup, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6cuckoo_10cuckoohash_lookup},
  {"has_key", (PyCFunction)__pyx_f_6cuckoo_10cuckoohash_has_key, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6cuckoo_10cuckoohash_has_key},
  {"insert", (PyCFunction)__pyx_f_6cuckoo_10cuckoohash_insert, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6cuckoo_10cuckoohash_insert},
  {"get", (PyCFunction)__pyx_f_6cuckoo_10cuckoohash_get, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6cuckoo_10cuckoohash_get},
  {"keys", (PyCFunction)__pyx_f_6cuckoo_10cuckoohash_keys, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6cuckoo_10cuckoohash_keys},
  {"values", (PyCFunction)__pyx_f_6cuckoo_10cuckoohash_values, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6cuckoo_10cuckoohash_values},
  {"items", (PyCFunction)__pyx_f_6cuckoo_10cuckoohash_items, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6cuckoo_10cuckoohash_items},
  {"iteritems", (PyCFunction)__pyx_f_6cuckoo_10cuckoohash_iteritems, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6cuckoo_10cuckoohash_iteritems},
  {"iterkeys", (PyCFunction)__pyx_f_6cuckoo_10cuckoohash_iterkeys, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6cuckoo_10cuckoohash_iterkeys},
  {"itervalues", (PyCFunction)__pyx_f_6cuckoo_10cuckoohash_itervalues, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6cuckoo_10cuckoohash_itervalues},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_cuckoohash = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_cuckoohash = {
  __pyx_f_6cuckoo_10cuckoohash___len__, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  __pyx_sq_item_6cuckoo_cuckoohash, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_cuckoohash = {
  __pyx_f_6cuckoo_10cuckoohash___len__, /*mp_length*/
  __pyx_f_6cuckoo_10cuckoohash___getitem__, /*mp_subscript*/
  __pyx_mp_ass_subscript_6cuckoo_cuckoohash, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_cuckoohash = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_6cuckoo_cuckoohash = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "cuckoo.cuckoohash", /*tp_name*/
  sizeof(struct __pyx_obj_6cuckoo_cuckoohash), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_6cuckoo_cuckoohash, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_cuckoohash, /*tp_as_number*/
  &__pyx_tp_as_sequence_cuckoohash, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_cuckoohash, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_cuckoohash, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  "cuckoohash() -> new empty Cuckoo Hash table\n\n    cuckoohash(size=n) -> Create a new Cuckoo Hash table with \n        initial size n. \n        Note: the table will automatically grow as needed.\n    cuckoohash(seq=seq) -> Create a new Cuckoo Hash table as if via:\n        c = cuckoohash()\n        for k, v in seq: c[k] = v\n\n    ", /*tp_doc*/
  __pyx_tp_traverse_6cuckoo_cuckoohash, /*tp_traverse*/
  __pyx_tp_clear_6cuckoo_cuckoohash, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  __pyx_f_6cuckoo_10cuckoohash___iter__, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_6cuckoo_cuckoohash, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_6cuckoo_10cuckoohash___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_6cuckoo_cuckoohash, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

DL_EXPORT(void) initcuckoo(void); /*proto*/
DL_EXPORT(void) initcuckoo(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  __pyx_m = Py_InitModule4("cuckoo", __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; goto __pyx_L1;};
  __pyx_vtabptr_6cuckoo_cuckoohash = &__pyx_vtable_6cuckoo_cuckoohash;
  __pyx_vtable_6cuckoo_cuckoohash.__cuckoo_gather = (void *)__pyx_f_6cuckoo_10cuckoohash___cuckoo_gather;
  if (PyType_Ready(&__pyx_type_6cuckoo_cuckoohash) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_6cuckoo_cuckoohash.tp_dict, __pyx_vtabptr_6cuckoo_cuckoohash) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "cuckoohash", (PyObject *)&__pyx_type_6cuckoo_cuckoohash) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  __pyx_ptype_6cuckoo_cuckoohash = &__pyx_type_6cuckoo_cuckoohash;

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":32 */
  if (PyObject_SetAttr(__pyx_m, __pyx_n___author__, __pyx_k1p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":33 */
  if (PyObject_SetAttr(__pyx_m, __pyx_n___copyright__, __pyx_k2p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":34 */
  if (PyObject_SetAttr(__pyx_m, __pyx_n___license__, __pyx_n_GPL2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":35 */
  if (PyObject_SetAttr(__pyx_m, __pyx_n___url__, __pyx_k4p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":36 */
  if (PyObject_SetAttr(__pyx_m, __pyx_n___version__, __pyx_k5p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":101 */
  __pyx_1 = PyInt_FromLong(1024); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_k6 = __pyx_1;
  __pyx_1 = 0;
  __pyx_2 = PyList_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_k7 = __pyx_2;
  __pyx_2 = 0;

  /* "/home/jose/src/ckhash-0.4.2/python/cuckoo.pyx":188 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("cuckoo");
}

static char *__pyx_filenames[] = {
  "cuckoo.pyx",
};
statichere char **__pyx_f = __pyx_filenames;

/* Runtime support code */

static void __Pyx_WriteUnraisable(char *name) {
    PyObject *old_exc, *old_val, *old_tb;
    PyObject *ctx;
    PyErr_Fetch(&old_exc, &old_val, &old_tb);
    ctx = PyString_FromString(name);
    PyErr_Restore(old_exc, old_val, old_tb);
    if (!ctx)
        ctx = Py_None;
    PyErr_WriteUnraisable(ctx);
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_UnpackError(void) {
    PyErr_SetString(PyExc_ValueError, "unpack sequence of wrong size");
}

static PyObject *__Pyx_UnpackItem(PyObject *seq, int i) {
  PyObject *item;
  if (!(item = PySequence_GetItem(seq, i))) {
    if (PyErr_ExceptionMatches(PyExc_IndexError))
    	__Pyx_UnpackError();
  }
  return item;
}

static int __Pyx_EndUnpack(PyObject *seq, int i) {
  PyObject *item;
  if (item = PySequence_GetItem(seq, i)) {
    Py_DECREF(item);
    __Pyx_UnpackError();
    return -1;
  }
  PyErr_Clear();
    return 0;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx__vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
